version: 2.1
jobs:
  build_debug:
    steps:
      - run: echo "build debug" > debug.txt
  test:
    steps:
      - run: test $(cat debug.txt) = "build debug"
workflows:
  build_debug_and_test:
    jobs:
      - build_debug
      - test
