version: 2.1
executors:
  my_executor:
    docker:
      - image: ubuntu:eoan-20190916
jobs:
  build_debug:
    executor: my_executor
    steps:
      - run:
          command: echo "build debug" > debug.txt
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  test:
    executor: my_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "$PWD"; test "$(cat debug.txt)" = "build debug"
workflows:
  build_debug_and_test:
    jobs:
      - build_debug
      - test:
          requires:
            - build_debug
